// Cognitive core: persistent state, reasoning, adaptation, recovery and evolution.
#include "jarvis/core/brain.hpp"

#include <algorithm>
#include <chrono>
#include <cmath>
#include <mutex>
#include <sstream>
#include <utility>

namespace jarvis::core {
namespace {
std::uint64_t now_ns() noexcept { return static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::system_clock::now().time_since_epoch()).count()); }
const std::string* string_value(const Attributes& data, const std::string& key) { const auto it = data.find(key); return it == data.end() ? nullptr : std::get_if<std::string>(&it->second); }
double double_value(const Attributes& data, const std::string& key, double fallback = 0.0) { const auto it = data.find(key); if (it == data.end()) return fallback; if (const auto value = std::get_if<double>(&it->second)) return *value; if (const auto value = std::get_if<std::int64_t>(&it->second)) return static_cast<double>(*value); return fallback; }
std::uint64_t integer_value(const Attributes& data, const std::string& key, std::uint64_t fallback = 0) { const auto it = data.find(key); if (it == data.end()) return fallback; if (const auto value = std::get_if<std::int64_t>(&it->second)) return *value < 0 ? fallback : static_cast<std::uint64_t>(*value); if (const auto value = std::get_if<double>(&it->second)) return *value < 0.0 ? fallback : static_cast<std::uint64_t>(*value); return fallback; }
std::string join_ids(const std::vector<std::string>& ids) { std::ostringstream out; for (std::size_t i = 0; i < ids.size(); ++i) { if (i != 0) out << '\x1f'; out << ids[i]; } return out.str(); }
std::vector<std::string> split_ids(const std::string& value) { std::vector<std::string> result; std::size_t start = 0; while (start <= value.size()) { const auto end = value.find('\x1f', start); const auto token = value.substr(start, end == std::string::npos ? std::string::npos : end - start); if (!token.empty()) result.push_back(token); if (end == std::string::npos) break; start = end + 1; } return result; }
GoalStatus goal_status_value(std::int64_t value) { switch (value) { case 0: return GoalStatus::pending; case 1: return GoalStatus::active; case 2: return GoalStatus::completed; case 3: return GoalStatus::abandoned; default: return GoalStatus::pending; } }
}
Brain::Brain(std::filesystem::path journal_path) : memory_(256, std::move(journal_path)), evolution_controller_(evolution_, evolution_history_) { const auto history = memory_.all(); for (const auto& event : history) replay(event); state_.events_seen = static_cast<std::uint64_t>(history.size()); if (!history.empty()) state_.cycle = history.back().sequence; sync_self_state(); }
void Brain::sync_self_state() { const auto goals = goals_model_.all(); std::vector<GoalState> active_goals; active_goals.reserve(goals.size()); for (const auto& goal : goals) if (goal.status == GoalStatus::active) active_goals.push_back(GoalState{goal.id, goal.priority, true}); self_state_model_.set_goals(std::move(active_goals)); const auto capability_health = self_model_.health(); self_state_model_.set_activity(state_.events_seen == 0 ? "idle" : "cognitive_processing"); self_state_model_.set_workload(std::clamp(std::max(state_.threat, 1.0 - capability_health.overall), 0.0, 1.0)); self_state_model_.set_uncertainty(std::clamp(1.0 - state_.attention, 0.0, 1.0)); self_state_model_.set_health(CognitiveHealth{std::clamp(capability_health.overall * (1.0 - state_.threat * 0.5), 0.0, 1.0), capability_health.overall, std::clamp(1.0 - state_.novelty * 0.1, 0.0, 1.0), capability_health.overall}); for (const auto& capability : self_model_.capabilities()) self_state_model_.set_resource_pressure(capability.name, std::clamp(1.0 - (capability.availability * capability.performance), 0.0, 1.0)); self_state_model_.advance_cycle(state_.events_seen); }
void Brain::replay(const Event& event) {
    state_.cycle = std::max(state_.cycle, event.sequence);
    if (event.kind == "goal_create") { const auto* id = string_value(event.data, "id"); const auto* description = string_value(event.data, "description"); if (id == nullptr || description == nullptr) return; Goal goal{*id, *description, double_value(event.data, "priority"), double_value(event.data, "progress"), integer_value(event.data, "created_cycle"), integer_value(event.data, "deadline_cycle"), goal_status_value(static_cast<std::int64_t>(integer_value(event.data, "status"))), string_value(event.data, "prerequisites") ? split_ids(*string_value(event.data, "prerequisites")) : std::vector<std::string>{}, string_value(event.data, "subgoals") ? split_ids(*string_value(event.data, "subgoals")) : std::vector<std::string>{}}; goals_model_.create(std::move(goal)); return; }
    if (event.kind == "goal_activate") { if (const auto* id = string_value(event.data, "id")) goals_model_.activate(*id); return; }
    if (event.kind == "goal_progress") { if (const auto* id = string_value(event.data, "id")) goals_model_.update_progress(*id, double_value(event.data, "progress")); return; }
    if (event.kind == "goal_complete") { if (const auto* id = string_value(event.data, "id")) goals_model_.complete(*id); return; }
    if (event.kind == "goal_abandon") { if (const auto* id = string_value(event.data, "id")) goals_model_.abandon(*id); return; }
    if (event.kind == "goal_priority") { if (const auto* id = string_value(event.data, "id")) goals_model_.set_priority(*id, double_value(event.data, "priority")); return; }
    if (event.kind == "prediction") { const auto* key = string_value(event.data, "key"); const auto value = event.data.find("value"); if (key == nullptr || value == event.data.end()) return; PredictionContext context{}; if (const auto* members = string_value(event.data, "concept_members")) context.concept_members = split_ids(*members); context.evidence_strength = std::clamp(double_value(event.data, "evidence_strength"), 0.0, 1.0); predictions_.push_back(Prediction{*key, value->second, std::clamp(double_value(event.data, "confidence"), 0.0, 1.0), event.sequence, false, 0.0, std::move(context)}); return; }
    if (event.kind == "prediction_outcome") { const auto* key = string_value(event.data, "key"); if (key == nullptr) return; const auto prediction_sequence = integer_value(event.data, "prediction_sequence", 0); Prediction* prediction = prediction_sequence != 0 ? find_prediction(prediction_sequence) : find_latest_unresolved_prediction(*key); if (prediction == nullptr || prediction->resolved) return; prediction->resolved = true; prediction->error = std::clamp(double_value(event.data, "error", 1.0), 0.0, 1.0); const auto actual = event.data.find("actual"); if (actual != event.data.end()) if (const auto predicted = std::get_if<double>(&prediction->predicted)) if (const auto observed = std::get_if<double>(&actual->second)) { adaptation_.observe(*key, *predicted, *observed); association_.apply_prediction_feedback(prediction->context.concept_members, prediction->error <= 0.0, prediction->context.evidence_strength, event.sequence); developmental_learning_.observe_association(*key, "prediction_outcome", LearningSignal{prediction->error, 1.0 - prediction->error, prediction->confidence, state_.novelty}); } return; }
    if (event.kind == "evolution_evaluated") { const auto* id = string_value(event.data, "experiment_id"); const auto* key = string_value(event.data, "key"); if (id != nullptr && key != nullptr) evolution_history_.append(EvolutionHistoryRecord{*id, *key, EvolutionRecordAction::Evaluated, static_cast<ExperimentOutcome>(integer_value(event.data, "outcome")), double_value(event.data, "baseline"), double_value(event.data, "candidate"), double_value(event.data, "confidence"), 0, "replayed", {}}); return; }
    if (event.kind == "evolution_register") { if (const auto* key = string_value(event.data, "key")) evolution_.register_parameter(*key, double_value(event.data, "initial")); return; }
    if (event.kind == "evolution_fitness") { if (const auto* key = string_value(event.data, "key")) evolution_.observe_fitness(*key, double_value(event.data, "fitness")); return; }
    if (event.kind == "evolution_adopt") { const auto* key = string_value(event.data, "key"); if (key != nullptr) { const EvolutionProposal proposal{*key, double_value(event.data, "current"), double_value(event.data, "proposed"), double_value(event.data, "expected_gain"), double_value(event.data, "confidence")}; evolution_.adopt(proposal); evolution_history_.append(EvolutionHistoryRecord{string_value(event.data, "experiment_id") ? *string_value(event.data, "experiment_id") : "replayed", *key, EvolutionRecordAction::Adopted, ExperimentOutcome::Improved, double_value(event.data, "baseline", proposal.current), double_value(event.data, "candidate", proposal.proposed), proposal.confidence, 0, "replayed", {}}); } return; }
    if (event.kind == "evolution_rollback") { const auto* key = string_value(event.data, "key"); if (key != nullptr) { evolution_.rollback(*key); evolution_history_.append(EvolutionHistoryRecord{string_value(event.data, "experiment_id") ? *string_value(event.data, "experiment_id") : "replayed", *key, EvolutionRecordAction::RolledBack, ExperimentOutcome::Degraded, double_value(event.data, "baseline", 0.0), double_value(event.data, "candidate", double_value(event.data, "observed_delta", 0.0)), 0.0, 0, string_value(event.data, "reason") ? *string_value(event.data, "reason") : "replayed", {}}); } return; }
    if (event.kind == "resilience_isolate") { if (const auto* component = string_value(event.data, "component")) resilience_.isolate(*component); return; }
    if (event.kind == "resilience_recover") { if (const auto* component = string_value(event.data, "component")) resilience_.recover(*component, double_value(event.data, "health")); return; }
    if (event.kind == "capability_observe") { if (const auto* name = string_value(event.data, "name")) self_model_.observe_capability(*name, double_value(event.data, "availability"), double_value(event.data, "performance")); return; }
    if (event.kind == "capability_isolate") { if (const auto* name = string_value(event.data, "name")) self_model_.isolate(*name); return; }
    if (event.kind == "capability_restore") { if (const auto* name = string_value(event.data, "name")) self_model_.restore(*name, double_value(event.data, "availability"), double_value(event.data, "performance")); return; }
    if (event.kind != "observation" && event.kind != "learning") return;
    const double reliability = event.kind == "learning" ? std::clamp(double_value(event.data, "reliability", 0.5), 0.0, 1.0) : 0.7;
    if (event.kind == "learning") for (const auto& [key, value] : event.data) if (key != "reliability") { knowledge_.assimilate(Evidence{event.source, key, value, reliability}); break; }
    std::vector<Belief> before; before.reserve(beliefs_.size()); for (const auto& [_, belief] : beliefs_) before.push_back(belief);
    for (const auto& [key, value] : event.data) { if (event.kind == "learning" && key == "reliability") continue; const auto it = beliefs_.find(key); if (it == beliefs_.end()) beliefs_.emplace(key, Belief{key, value, reliability, 1, event.sequence}); else { const bool same = it->second.value == value; it->second.value = value; it->second.confidence = same ? std::min(0.999, it->second.confidence + (1.0 - it->second.confidence) * reliability) : std::max(0.05, it->second.confidence * (1.0 - reliability)); it->second.disputed = !same && it->second.observations > 0; ++it->second.observations; it->second.updated_sequence = event.sequence; } world_.observe(Fact{event.source, key, value, reliability, 1}); const auto subject = string_value(event.data, "subject"); const auto predicate = string_value(event.data, "predicate"); const auto object = string_value(event.data, "object"); if (subject != nullptr && predicate != nullptr && object != nullptr) world_.relate(Relation{*subject, *predicate, *object, reliability, event.sequence, false}); }
    std::vector<Belief> after; after.reserve(beliefs_.size()); for (const auto& [_, belief] : beliefs_) after.push_back(belief); causal_.observe_transition(before, after); association_.observe(before, after, event.sequence);
    if (event.kind == "observation") { const auto history = memory_.recent(2); std::vector<Event> previous; if (history.size() > 1) previous.push_back(history[1]); const double novelty = compute_novelty(event, previous); double strongest = 0.0; for (const auto& [_, belief] : beliefs_) strongest = std::max(strongest, belief.confidence); attention_state_ = attention_model_.score(event, novelty, strongest); threat_state_ = threat_model_.assess(event); state_.novelty = novelty; state_.attention = attention_state_.salience; state_.threat = threat_state_.score; const auto health = event.data.find("health"); if (health != event.data.end()) resilience_.observe(event.source, std::clamp(double_value(event.data, "health", 1.0), 0.0, 1.0)); }
}
Observation Brain::observe(Event event) { std::unique_lock lock(mutex_); event.timestamp_ns = event.timestamp_ns == 0 ? now_ns() : event.timestamp_ns; const auto previous = memory_.recent(1); const double novelty = compute_novelty(event, previous); event.sequence = memory_.append(event); if (event.sequence == 0) return Observation{}; ++state_.events_seen; state_.cycle = event.sequence; replay(event); state_.novelty = novelty; sync_self_state(); return Observation{std::move(event), novelty}; }
double Brain::learn(const Evidence& evidence) { std::unique_lock lock(mutex_); if (evidence.key.empty()) return 0.0; const double reliability = std::clamp(evidence.reliability, 0.0, 1.0); Event event{0, now_ns(), evidence.source, "learning", {{evidence.key, evidence.value}, {"reliability", reliability}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return 0.0; ++state_.events_seen; state_.cycle = event.sequence; replay(event); sync_self_state(); if (const auto* metric = knowledge_.source_metric(evidence.source)) return metric->reliability; return reliability; }
std::vector<Belief> Brain::beliefs() const { std::shared_lock lock(mutex_); std::vector<Belief> result; result.reserve(beliefs_.size()); for (const auto& [_, belief] : beliefs_) result.push_back(belief); return result; }
Prediction Brain::predict(std::string key, Scalar value, double confidence) { std::unique_lock lock(mutex_); if (key.empty()) return Prediction{}; Prediction prediction{std::move(key), std::move(value), std::clamp(confidence, 0.0, 1.0), 0, false, 0.0}; Event event{0, now_ns(), "brain", "prediction", {{"key", prediction.key}, {"value", prediction.predicted}, {"confidence", prediction.confidence}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return Prediction{}; replay(event); ++state_.events_seen; state_.cycle = event.sequence; const auto* stored = find_prediction(event.sequence); sync_self_state(); return stored == nullptr ? Prediction{} : *stored; }
bool Brain::resolve_prediction(const std::string& key, const Scalar& actual) { std::unique_lock lock(mutex_); const auto* prediction = find_latest_unresolved_prediction(key); if (prediction == nullptr) return false; return resolve_prediction(prediction->created_sequence, actual); }
bool Brain::resolve_prediction(std::uint64_t prediction_sequence, const Scalar& actual) { std::unique_lock lock(mutex_); const auto* prediction = find_prediction(prediction_sequence); if (prediction == nullptr || prediction->resolved || prediction->key.empty()) return false; double error = prediction->predicted == actual ? 0.0 : 1.0; if (const auto predicted = std::get_if<double>(&prediction->predicted)) if (const auto observed = std::get_if<double>(&actual)) error = std::clamp(std::abs(*observed - *predicted), 0.0, 1.0); Event event{0, now_ns(), "brain", "prediction_outcome", {{"key", prediction->key}, {"prediction_sequence", static_cast<std::int64_t>(prediction_sequence)}, {"actual", actual}, {"error", error}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return false; replay(event); ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return error == 0.0; }
const KnowledgeMetric* Brain::knowledge_source(const std::string& source) const noexcept { std::shared_lock lock(mutex_); return knowledge_.source_metric(source); }
const AdaptiveMetric* Brain::learning_metric(const std::string& key) const noexcept { std::shared_lock lock(mutex_); return adaptation_.metric(key); }
double Brain::learning_confidence(const std::string& key) const noexcept { std::shared_lock lock(mutex_); return std::clamp(adaptation_.confidence(key), 0.0, 1.0); }
std::vector<LearnedAssociation> Brain::developmental_associations() const { std::shared_lock lock(mutex_); return developmental_learning_.associations(); }
std::vector<LearnedStrategy> Brain::developmental_strategies() const { std::shared_lock lock(mutex_); return developmental_learning_.strategies(); }
const LearnedStrategy* Brain::developmental_best_strategy(const std::string& context) const noexcept { std::shared_lock lock(mutex_); return developmental_learning_.best_strategy(context); }
double Brain::learning_confidence(const std::string& key) const noexcept { std::shared_lock lock(mutex_); return std::clamp(adaptation_.confidence(key), 0.0, 1.0); }
std::vector<std::pair<std::string, Scalar>> Brain::simulate(const std::vector<Belief>& assumptions) const { std::shared_lock lock(mutex_); return causal_.predict(assumptions); }
SimulationResult Brain::simulate(const std::vector<Belief>& assumptions, std::size_t horizon) const { std::shared_lock lock(mutex_); return causal_.simulate(assumptions, horizon); }
std::vector<Association> Brain::associations() const { std::shared_lock lock(mutex_); return association_.all(); }
std::vector<Association> Brain::associated_with(const std::string& key, double minimum_strength) const { std::shared_lock lock(mutex_); return association_.related(key, minimum_strength); }
std::vector<AssociationInference> Brain::contextual_associations(const std::string& key, std::size_t max_hops, double minimum_strength) const { std::shared_lock lock(mutex_); return association_.contextual(key, max_hops, minimum_strength); }
std::vector<ConceptCandidate> Brain::concept_candidates(double minimum_strength, std::size_t minimum_shared_contexts) const { std::shared_lock lock(mutex_); return association_.concept_candidates(minimum_strength, minimum_shared_contexts); }
std::vector<ConceptCandidate> Brain::contextual_concepts(const std::string& key, double minimum_strength, std::size_t minimum_shared_contexts) const { std::shared_lock lock(mutex_); return association_.generalized_concepts(key, minimum_strength, minimum_shared_contexts); }
std::vector<ConceptMatch> Brain::generalized_concepts(const std::string& key, double minimum_strength, std::size_t minimum_shared_contexts, double minimum_similarity) const { std::shared_lock lock(mutex_); return association_.generalized_concepts(key, minimum_strength, minimum_shared_contexts, minimum_similarity); }
std::vector<CausalLink> Brain::causal_links() const { std::shared_lock lock(mutex_); return causal_.links(); }
std::vector<Decision> Brain::choose(const std::vector<CandidateAction>& actions) const { std::shared_lock lock(mutex_); const auto self = self_state_model_.snapshot(); const auto eligible = goals_model_.eligible(state_.cycle); const auto selected_intent = intent_model_.select(eligible, threat_state_.score, self.uncertainty, state_.cycle); const auto strategy = strategy_model_.formulate(selected_intent, attention_state_, threat_state_.score, self.uncertainty); const auto plan = planner_.build(actions, 1, strategy.planning); DecisionContext context; context.goal_priority = strategy.planning.goal_priority; context.goal_progress = strategy.planning.goal_progress; context.plan_expected_value = plan.expected_value; context.plan_risk = plan.risk; context.resource_budget = strategy.planning.resource_budget; context.uncertainty = strategy.planning.uncertainty; context.threat = strategy.planning.threat; context.deadline_pressure = strategy.planning.deadline_pressure; return decision_.decide(actions, context); }
std::vector<ActionAssessment> Brain::assess_actions(const std::vector<Decision>& decisions, ActionConstraints constraints) const { std::shared_lock lock(mutex_); return action_model_.assess(decisions, constraints); }
std::vector<CapabilityCandidate> Brain::evaluate_capabilities(const std::vector<CapabilityDescriptor>& capabilities, CapabilityConstraints constraints) const { std::shared_lock lock(mutex_); return CapabilityEvaluator{}.evaluate(capabilities, constraints); }
CapabilityExecutionResult Brain::execute_capability(const CapabilityDescriptor& capability, std::string input, std::vector<std::string> granted_permissions, double maximum_risk, CapabilityProvider provider) {
    if (provider.capability_id.empty() || !provider.execute) return {CapabilityExecutionStatus::rejected, capability.id, {}, {}, "capability_provider_required"};
    if (provider.capability_id != capability.id) return {CapabilityExecutionStatus::rejected, capability.id, {}, {}, "capability_provider_mismatch"};
    CapabilityExecutionBoundary boundary;
    if (!boundary.register_provider(std::move(provider))) return {CapabilityExecutionStatus::rejected, capability.id, {}, {}, "capability_provider_registration_failed"};
    const auto result = boundary.execute(CapabilityExecutionRequest{capability, std::move(input), std::move(granted_permissions), maximum_risk});
    if (!capability.id.empty()) { const double reliability = result.status == CapabilityExecutionStatus::succeeded ? 1.0 : result.status == CapabilityExecutionStatus::unavailable ? 0.25 : 0.0; std::unique_lock lock(mutex_); Event event{0, now_ns(), result.provider.empty() ? "capability_executor" : result.provider, "capability_execution", {{"capability_id", capability.id}, {"status", static_cast<std::int64_t>(result.status)}, {"provider", result.provider}, {"reason", result.reason}, {"output", result.output}, {"reliability", reliability}}}; event.sequence = memory_.append(event); if (event.sequence != 0) { ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); } }
    return result;
}
Plan Brain::plan(const std::vector<CandidateAction>& actions, std::size_t horizon) const { std::shared_lock lock(mutex_); return planner_.build(actions, horizon); }
Plan Brain::plan(const std::vector<CandidateAction>& actions, std::size_t horizon, const PlanningContext& context) const { std::shared_lock lock(mutex_); return planner_.build(actions, horizon, context); }
Reflection Brain::reflect() const { std::shared_lock lock(mutex_); std::vector<Belief> beliefs; beliefs.reserve(beliefs_.size()); for (const auto& [_, belief] : beliefs_) beliefs.push_back(belief); std::vector<Prediction> predictions; predictions.reserve(predictions_.size()); for (const auto& prediction : predictions_) predictions.push_back(prediction); return reflection_model_.evaluate(beliefs, predictions); }
AttentionSignal Brain::attention() const { std::shared_lock lock(mutex_); return attention_state_; }
ThreatAssessment Brain::threat() const { std::shared_lock lock(mutex_); return threat_state_; }
std::vector<RecoveryPlan> Brain::recovery_options() const { std::shared_lock lock(mutex_); return resilience_.required_recovery(); }
SelfTestReport Brain::self_test() const {
    std::shared_lock lock(mutex_);
    const auto history = memory_.all();
    std::vector<DiagnosticCheck> checks;
    checks.push_back({"journal", "sequence-monotonic", [history] { std::uint64_t previous = 0; for (const auto& event : history) { if (event.sequence == 0 || (previous != 0 && event.sequence <= previous)) return false; previous = event.sequence; } return true; }});
    checks.push_back({"brain", "cycle-consistent", [this] { return state_.cycle >= state_.events_seen || state_.events_seen == 0; }});
    checks.push_back({"memory", "journal-readable", [history] { return true; }});
    checks.push_back({"goals", "goal-state-readable", [this] { return !goals_model_.all().empty() || true; }});
    checks.push_back({"self-model", "health-bounded", [this] { const auto h = self_model_.health(); return h.overall >= 0.0 && h.overall <= 1.0; }});
    checks.push_back({"cognition", "state-bounded", [this] { return state_.novelty >= 0.0 && state_.novelty <= 1.0 && state_.attention >= 0.0 && state_.attention <= 1.0 && state_.threat >= 0.0 && state_.threat <= 1.0; }});
    return self_testing_model_.run(checks);
}
SelfHealingResult Brain::self_heal(const std::string& component, std::function<bool(const std::string&)> repair, std::function<bool(const std::string&)> verify) {
    if (component.empty() || !repair || !verify) return {component, HealingState::RecoveryFailed, "invalid_healing_request"};
    const auto result = self_testing_model_.heal(component, [component, &repair] { return repair(component); }, [component, &verify] { return verify(component); });
    if (result.state == HealingState::Recovered) { recover(component, 1.0); }
    return result;
}
bool Brain::create_goal(Goal goal) { std::unique_lock lock(mutex_); if (goal.id.empty() || goal.description.empty()) return false; goal.priority = std::clamp(goal.priority, 0.0, 1.0); goal.progress = std::clamp(goal.progress, 0.0, 1.0); const std::uint64_t created_cycle = state_.cycle + 1; goal.created_cycle = created_cycle; Event event{0, now_ns(), "brain", "goal_create", {{"id", goal.id}, {"description", goal.description}, {"priority", goal.priority}, {"progress", goal.progress}, {"created_cycle", static_cast<std::int64_t>(goal.created_cycle)}, {"deadline_cycle", static_cast<std::int64_t>(goal.deadline_cycle)}, {"status", static_cast<std::int64_t>(goal.status)}, {"prerequisites", join_ids(goal.prerequisites)}, {"subgoals", join_ids(goal.subgoals)}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return false; goal.created_cycle = event.sequence; if (!goals_model_.create(std::move(goal))) return false; ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
bool Brain::activate_goal(const std::string& id) { std::unique_lock lock(mutex_); if (!goals_model_.activate(id)) return false; Event event{0, now_ns(), "brain", "goal_activate", {{"id", id}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return false; ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
bool Brain::update_goal_progress(const std::string& id, double progress) { std::unique_lock lock(mutex_); const double bounded = std::clamp(progress, 0.0, 1.0); if (!goals_model_.update_progress(id, bounded)) return false; Event event{0, now_ns(), "brain", "goal_progress", {{"id", id}, {"progress", bounded}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return false; ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
bool Brain::complete_goal(const std::string& id) { std::unique_lock lock(mutex_); if (!goals_model_.complete(id)) return false; Event event{0, now_ns(), "brain", "goal_complete", {{"id", id}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return false; ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
bool Brain::abandon_goal(const std::string& id) { std::unique_lock lock(mutex_); if (!goals_model_.abandon(id)) return false; Event event{0, now_ns(), "brain", "goal_abandon", {{"id", id}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return false; ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
bool Brain::set_goal_priority(const std::string& id, double priority) { std::unique_lock lock(mutex_); const double bounded = std::clamp(priority, 0.0, 1.0); if (!goals_model_.set_priority(id, bounded)) return false; Event event{0, now_ns(), "brain", "goal_priority", {{"id", id}, {"priority", bounded}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return false; ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
const Goal* Brain::goal(const std::string& id) const noexcept { std::shared_lock lock(mutex_); return goals_model_.get(id); }
std::vector<Goal> Brain::goals() const { std::shared_lock lock(mutex_); return goals_model_.all(); }
std::vector<Goal> Brain::eligible_goals() const { std::shared_lock lock(mutex_); return goals_model_.eligible(state_.cycle); }
void Brain::observe_capability(std::string name, double availability, double performance) { std::unique_lock lock(mutex_); if (name.empty()) return; const double bounded_availability = std::clamp(availability, 0.0, 1.0); const double bounded_performance = std::clamp(performance, 0.0, 1.0); Event event{0, now_ns(), "brain", "capability_observe", {{"name", name}, {"availability", bounded_availability}, {"performance", bounded_performance}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return; self_model_.observe_capability(name, bounded_availability, bounded_performance); ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); }
bool Brain::isolate_capability(const std::string& name) { std::unique_lock lock(mutex_); if (name.empty() || !self_model_.isolate(name)) return false; Event event{0, now_ns(), "brain", "capability_isolate", {{"name", name}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return false; ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
bool Brain::restore_capability(const std::string& name, double availability, double performance) { std::unique_lock lock(mutex_); const double bounded_availability = std::clamp(availability, 0.0, 1.0); const double bounded_performance = std::clamp(performance, 0.0, 1.0); if (name.empty() || !self_model_.restore(name, bounded_availability, bounded_performance)) return false; Event event{0, now_ns(), "brain", "capability_restore", {{"name", name}, {"availability", bounded_availability}, {"performance", bounded_performance}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return false; ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
bool Brain::isolate(const std::string& component) { std::unique_lock lock(mutex_); if (component.empty() || !resilience_.isolate(component)) return false; Event event{0, now_ns(), "brain", "resilience_isolate", {{"component", component}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return false; ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
bool Brain::recover(const std::string& component, double restored_health) { std::unique_lock lock(mutex_); const double health = std::clamp(restored_health, 0.0, 1.0); if (component.empty() || !resilience_.recover(component, health)) return false; Event event{0, now_ns(), "brain", "resilience_recover", {{"component", component}, {"health", health}}}; event.sequence = memory_.append(event); if (event.sequence == 0) { resilience_.isolate(component); return false; } ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
void Brain::register_evolution_parameter(std::string key, double initial) { std::unique_lock lock(mutex_); if (key.empty()) return; Event event{0, now_ns(), "brain", "evolution_register", {{"key", key}, {"initial", initial}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return; evolution_.register_parameter(key, initial); ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); }
void Brain::observe_evolution_fitness(const std::string& key, double fitness) { std::unique_lock lock(mutex_); if (key.empty()) return; Event event{0, now_ns(), "brain", "evolution_fitness", {{"key", key}, {"fitness", fitness}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return; evolution_.observe_fitness(key, fitness); ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); }
std::vector<EvolutionProposal> Brain::evolution_options() const { std::shared_lock lock(mutex_); return evolution_.propose(); }
bool Brain::adopt_evolution(const EvolutionProposal& proposal) { std::unique_lock lock(mutex_); if (proposal.key.empty() || !evolution_.adopt(proposal)) return false; Event event{0, now_ns(), "brain", "evolution_adopt", {{"key", proposal.key}, {"current", proposal.current}, {"proposed", proposal.proposed}, {"expected_gain", proposal.expected_gain}, {"confidence", proposal.confidence}}}; event.sequence = memory_.append(event); if (event.sequence == 0) { evolution_.rollback(proposal.key); return false; } ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
bool Brain::rollback_evolution(const std::string& key) { std::unique_lock lock(mutex_); if (key.empty() || !evolution_.rollback(key)) return false; Event event{0, now_ns(), "brain", "evolution_rollback", {{"key", key}}}; event.sequence = memory_.append(event); if (event.sequence == 0) return false; ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
bool Brain::adopt_evolution_experiment(EvolutionExperiment& experiment) { std::unique_lock lock(mutex_); if (!evolution_controller_.adopt(experiment)) return false; Event event{0, now_ns(), "brain", "evolution_adopt", {{"key", experiment.proposal.key}, {"current", experiment.proposal.current}, {"proposed", experiment.proposal.proposed}, {"expected_gain", experiment.proposal.expected_gain}, {"confidence", experiment.proposal.confidence}}}; event.sequence = memory_.append(event); if (event.sequence == 0) { evolution_.rollback(experiment.proposal.key); return false; } ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); return true; }
CanaryDecision Brain::observe_evolution_canary(const std::string& parameter_key, const std::string& experiment_id, CanaryObservation observation) { std::unique_lock lock(mutex_); const auto decision = evolution_controller_.observe_canary(parameter_key, experiment_id, observation); if (decision.rollback) { Event event{0, now_ns(), "brain", "evolution_rollback", {{"key", parameter_key}, {"experiment_id", experiment_id}, {"reason", decision.reason}, {"observed_delta", decision.mean_delta}}}; event.sequence = memory_.append(event); if (event.sequence != 0) { ++state_.events_seen; state_.cycle = event.sequence; sync_self_state(); } } return decision; }
std::vector<EvolutionHistoryRecord> Brain::evolution_history() const { std::shared_lock lock(mutex_); return evolution_history_.records(); }
BrainSnapshot Brain::snapshot() const { std::shared_lock lock(mutex_); BrainSnapshot snapshot; snapshot.state = state_; snapshot.self_state = self_state_model_.snapshot(); for (const auto& [_, belief] : beliefs_) snapshot.beliefs.push_back(belief); for (const auto& prediction : predictions_) snapshot.predictions.push_back(prediction); snapshot.causal_links = causal_.links(); snapshot.goals = goals_model_.all(); return snapshot; }
BrainState Brain::state() const { std::shared_lock lock(mutex_); return state_; }
bool Brain::append_goal_event(const Event& event) { Event persisted = event; persisted.timestamp_ns = persisted.timestamp_ns == 0 ? now_ns() : persisted.timestamp_ns; persisted.sequence = memory_.append(persisted); if (persisted.sequence == 0) return false; ++state_.events_seen; state_.cycle = persisted.sequence; sync_self_state(); return true; }
} // namespace jarvis::core
