#include "jarvis/core/brain.hpp"

#include <cassert>
#include <cmath>
#include <filesystem>
#include <iostream>

using namespace jarvis::core;

int main() {
    const auto path = std::filesystem::temp_directory_path() / "jarvis_affective_brain_decision.bin";
    std::error_code ec;
    std::filesystem::remove(path, ec);
    std::filesystem::remove(path.string() + ".meta", ec);

    Brain brain(path);
    CandidateAction reversible{"reversible", 0.3, 0.2, 0.2, 1.0, 0.1, 0.1, 0.4};
    CandidateAction irreversible{"irreversible", 0.3, 0.2, 0.2, 0.1, 0.1, 0.1, 0.4};
    const std::vector<CandidateAction> actions{reversible, irreversible};

    const auto neutral = brain.choose_with_affect(actions);
    assert(neutral.size() == 2);

    const auto observation = brain.observe(Event{
        0, 0, "test", "observation",
        {{"novelty", 1.0}, {"salience", 1.0}, {"uncertainty", 1.0}, {"outcome", -1.0}, {"confidence", 0.1}}});
    const auto affected_state = brain.affective_state();
    assert(affected_state.updates > 0);
    assert(std::isfinite(affected_state.valence));
    assert(std::isfinite(affected_state.arousal));
    assert(std::isfinite(affected_state.uncertainty));
    assert(std::isfinite(affected_state.tension));

    const auto consolidated = brain.memory().salient(8);
    bool found_observation = false;
    for (const auto& record : consolidated) {
        if (record.event.sequence == observation.event.sequence) {
            found_observation = true;
            assert(record.salience >= 0.0 && record.salience <= 1.0);
            assert(record.salience > 0.0);
            break;
        }
    }
    assert(found_observation);

    const ActionAssessment assessment{reversible, ActionDisposition::execute, true, 1.0, "test"};
    brain.execute_action(
        assessment,
        [](const CandidateAction&) { return false; },
        [](const CandidateAction&) { return false; });

    const auto affected = brain.choose_with_affect(actions);
    assert(affected.size() == 2);
    assert(affected.front().action.name == "reversible");

    Brain restored(path);
    const auto restored_state = restored.affective_state();
    // Replay must include the consequence events generated by action execution.
    // The exact update count is an implementation detail of the event stream;
    // the invariant is that replay reconstructs additional affective experience
    // beyond the observation that preceded the action.
    assert(restored_state.updates > affected_state.updates);
    assert(std::isfinite(restored_state.valence));
    assert(std::isfinite(restored_state.arousal));
    assert(std::isfinite(restored_state.uncertainty));
    assert(std::isfinite(restored_state.tension));

    const auto replayed = restored.choose_with_affect(actions);
    assert(replayed.size() == 2);
    assert(replayed.front().action.name == affected.front().action.name);

    std::filesystem::remove(path, ec);
    std::filesystem::remove(path.string() + ".meta", ec);
    std::cout << "affective_brain_decision_suite: PASS\n";
    return 0;
}
