#pragma once
#include "event.hpp"
#include "memory.hpp"
#include "world_model.hpp"
#include "cognition.hpp"
#include "association_model.hpp"
#include "causal_model.hpp"
#include "decision.hpp"
#include "action_model.hpp"
#include "action_execution.hpp"
#include "capability_evaluator.hpp"
#include "capability_execution.hpp"
#include "adaptation.hpp"
#include "learning_loop.hpp"
#include "attention.hpp"
#include "threat.hpp"
#include "resilience.hpp"
#include "evolution.hpp"
#include "evolution_experiment.hpp"
#include "evolution_controller.hpp"
#include "planning.hpp"
#include "reflection.hpp"
#include "knowledge.hpp"
#include "self_model.hpp"
#include "self_state.hpp"
#include "self_testing.hpp"
#include "goals.hpp"
#include "cognitive_goal_outcome.hpp"
#include "intent.hpp"
#include "strategy.hpp"
#include "developmental_learning.hpp"
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <functional>
#include <mutex>
#include <shared_mutex>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
namespace jarvis::core {
struct BrainState { std::uint64_t cycle{0}; std::uint64_t events_seen{0}; double novelty{0.0}; double attention{0.0}; double threat{0.0}; };
struct BrainSnapshot { BrainState state{}; SelfState self_state{}; std::vector<Belief> beliefs; std::vector<Prediction> predictions; std::vector<CausalLink> causal_links; std::vector<Goal> goals; };
class Brain {
public:
 explicit Brain(std::filesystem::path journal_path = "data/brain/continuity.bin");
 Observation observe(Event event); double learn(const Evidence& evidence);
 LearningCycle learn_from_prediction(const std::string& key, const Scalar& actual, double fitness) { std::unique_lock lock(mutex_); LearningCycle cycle{}; if (key.empty() || !std::isfinite(fitness)) return cycle; const auto* prediction = find_latest_unresolved_prediction(key); if (prediction == nullptr || prediction->resolved) return cycle; const auto predicted = std::get_if<double>(&prediction->predicted); const auto observed = std::get_if<double>(&actual); if (predicted == nullptr || observed == nullptr || !std::isfinite(*predicted) || !std::isfinite(*observed)) return cycle; const double error = std::clamp(std::abs(*observed - *predicted), 0.0, 1.0); Event outcome{0, 0, "brain", "prediction_outcome", {{"key", key}, {"prediction_sequence", static_cast<std::int64_t>(prediction->created_sequence)}, {"actual", actual}, {"error", error}}}; outcome.sequence = memory_.append(outcome); if (outcome.sequence == 0) return cycle; replay(outcome); ++state_.events_seen; state_.cycle = outcome.sequence; const double bounded_fitness = std::clamp(fitness, -1.0, 1.0); Event fitness_event{0, 0, "learning_loop", "evolution_fitness", {{"key", key}, {"fitness", bounded_fitness}}}; fitness_event.sequence = memory_.append(fitness_event); if (fitness_event.sequence == 0) return cycle; ++state_.events_seen; state_.cycle = fitness_event.sequence; cycle = learning_loop_.process(LearningFeedback{key, std::clamp(*predicted, 0.0, 1.0), std::clamp(*observed, 0.0, 1.0), bounded_fitness}, adaptation_, evolution_); for (const auto& proposal : cycle.proposals) { if (proposal.key != key || proposal.current == proposal.proposed) continue; const auto* parameter = evolution_.parameter(key); if (parameter == nullptr || parameter->value != proposal.proposed) continue; Event adoption{0, 0, "learning_loop", "evolution_adopt", {{"key", key}, {"current", proposal.current}, {"proposed", proposal.proposed}, {"expected_gain", proposal.expected_gain}, {"confidence", proposal.confidence}}}; adoption.sequence = memory_.append(adoption); if (adoption.sequence != 0) { ++state_.events_seen; state_.cycle = adoption.sequence; } break; } sync_self_state(); return cycle; }
 std::vector<Belief> beliefs() const; Prediction predict(std::string key, Scalar value, double confidence); Prediction predict_with_context(std::string key, Scalar value, double confidence, double minimum_strength = 0.5, std::size_t minimum_shared_contexts = 2); bool resolve_prediction(const std::string& key, const Scalar& actual); bool resolve_prediction(std::uint64_t prediction_sequence, const Scalar& actual);
 bool assimilate_goal_outcome(const GoalOutcomeEvidence& evidence) { std::unique_lock lock(mutex_); if (evidence.goal_id.empty()) return false; const auto* existing = goals_model_.get(evidence.goal_id); if (existing == nullptr || existing->status == GoalStatus::completed || existing->status == GoalStatus::abandoned) return false; GoalOutcomeEvidence normalized = evidence; normalized.normalize(); const double before = existing->progress; const double after = normalized.completed ? 1.0 : std::clamp(normalized.progress_after, 0.0, 1.0); Event progress_event{0, 0, "goal_feedback", "goal_progress", {{"id", normalized.goal_id}, {"progress", after}, {"previous_progress", before}, {"delta", after - before}, {"completed", normalized.completed || after >= 1.0}, {"confidence", normalized.confidence}}}; progress_event.sequence = memory_.append(progress_event); if (progress_event.sequence == 0) return false; replay(progress_event); ++state_.events_seen; state_.cycle = progress_event.sequence; if (normalized.completed || after >= 1.0) { Event completion_event{0, 0, "goal_feedback", "goal_complete", {{"id", normalized.goal_id}}}; completion_event.sequence = memory_.append(completion_event); if (completion_event.sequence == 0) return false; replay(completion_event); ++state_.events_seen; state_.cycle = completion_event.sequence; } sync_self_state(); return true; }
 std::vector<std::pair<std::string, Scalar>> simulate(const std::vector<Belief>& assumptions) const; SimulationResult simulate(const std::vector<Belief>& assumptions, std::size_t horizon) const;
 std::vector<Association> associations() const; std::vector<Association> associated_with(const std::string& key, double minimum_strength = 0.5) const; std::vector<AssociationInference> contextual_associations(const std::string& key, std::size_t max_hops = 2, double minimum_strength = 0.25) const; std::vector<ConceptCandidate> concept_candidates(double minimum_strength = 0.5, std::size_t minimum_shared_contexts = 2) const; std::vector<ConceptCandidate> contextual_concepts(const std::string& key, double minimum_strength = 0.5, std::size_t minimum_shared_contexts = 2) const; std::vector<ConceptMatch> generalized_concepts(const std::string& key, double minimum_strength = 0.5, std::size_t minimum_shared_contexts = 2, double minimum_similarity = 0.5) const;
 std::vector<CausalLink> causal_links() const; std::vector<Decision> choose(const std::vector<CandidateAction>& actions) const; Plan plan(const std::vector<CandidateAction>& actions, std::size_t horizon) const; Plan plan(const std::vector<CandidateAction>& actions, std::size_t horizon, const PlanningContext& context) const; std::vector<ActionAssessment> assess_actions(const std::vector<Decision>& decisions, ActionConstraints constraints = {}) const; std::vector<CapabilityCandidate> evaluate_capabilities(const std::vector<CapabilityDescriptor>& capabilities, CapabilityConstraints constraints = {}) const; CapabilityExecutionResult execute_capability(const CapabilityDescriptor& capability, std::string input, std::vector<std::string> granted_permissions = {}, double maximum_risk = 1.0, CapabilityProvider provider = {});
 ActionExecutionResult execute_action(const ActionAssessment& assessment, std::function<bool(const CandidateAction&)> execute, std::function<bool(const CandidateAction&)> verify, std::function<bool(const CandidateAction&)> rollback = {}, ActionAuthorizationContext authorization = {}) { std::unique_lock lock(mutex_); ActionExecutionRequest request{assessment, std::move(execute), std::move(verify), std::move(rollback), std::move(authorization)}; const auto result = ActionExecutor{}.run(request); const double reliability = result.status == ActionExecutionStatus::verified ? 1.0 : result.status == ActionExecutionStatus::rolled_back ? 0.25 : 0.5; if (!result.action.name.empty()) { Event action_event{0, 0, "brain", "action_outcome", {{"action", result.action.name}, {"status", static_cast<std::int64_t>(result.status)}, {"authorized", result.authorized}, {"executed", result.executed}, {"verified", result.verified}, {"rolled_back", result.rolled_back}, {"reason", result.reason}, {"reliability", reliability}}}; action_event.sequence = memory_.append(action_event); if (action_event.sequence != 0) { ++state_.events_seen; state_.cycle = action_event.sequence; } Event learning_event{0, 0, "action_executor", "learning", {{"action." + result.action.name, Scalar{result.reason}}, {"reliability", reliability}}}; learning_event.sequence = memory_.append(learning_event); if (learning_event.sequence != 0) { ++state_.events_seen; state_.cycle = learning_event.sequence; replay(learning_event); } } sync_self_state(); return result; }
 Reflection reflect() const; const KnowledgeMetric* knowledge_source(const std::string& source) const noexcept; const AdaptiveMetric* learning_metric(const std::string& key) const noexcept; double learning_confidence(const std::string& key) const noexcept;
 std::vector<LearnedAssociation> developmental_associations() const;
 std::vector<LearnedStrategy> developmental_strategies() const;
 const LearnedStrategy* developmental_best_strategy(const std::string& context) const noexcept; const StrategyParameter* evolution_parameter(const std::string& key) const noexcept { std::shared_lock lock(mutex_); return evolution_.parameter(key); } AttentionSignal attention() const; ThreatAssessment threat() const; Intent intent() const { std::shared_lock lock(mutex_); return intent_model_.select(goals_model_.eligible(state_.cycle), threat_state_.score, self_state_model_.snapshot().uncertainty, state_.cycle); } StrategyContext strategy() const { std::shared_lock lock(mutex_); const auto self = self_state_model_.snapshot(); const auto current_intent = intent_model_.select(goals_model_.eligible(state_.cycle), threat_state_.score, self.uncertainty, state_.cycle); return strategy_model_.formulate(current_intent, attention_state_, threat_state_.score, self.uncertainty); }
 std::vector<RecoveryPlan> recovery_options() const; bool isolate(const std::string& component); bool recover(const std::string& component, double restored_health); SelfTestReport self_test() const; SelfHealingResult self_heal(const std::string& component, std::function<bool(const std::string&)> repair, std::function<bool(const std::string&)> verify);
 void register_evolution_parameter(std::string key, double initial); void observe_evolution_fitness(const std::string& key, double fitness); std::vector<EvolutionProposal> evolution_options() const; bool adopt_evolution(const EvolutionProposal& proposal); bool rollback_evolution(const std::string& key); bool adopt_evolution_experiment(EvolutionExperiment& experiment); CanaryDecision observe_evolution_canary(const std::string& parameter_key, const std::string& experiment_id, CanaryObservation observation); std::vector<EvolutionHistoryRecord> evolution_history() const;
 void observe_capability(std::string name, double availability, double performance); bool isolate_capability(const std::string& name); bool restore_capability(const std::string& name, double availability, double performance); bool create_goal(Goal goal); bool activate_goal(const std::string& id); bool update_goal_progress(const std::string& id, double progress); bool complete_goal(const std::string& id); bool abandon_goal(const std::string& id); bool set_goal_priority(const std::string& id, double priority); const Goal* goal(const std::string& id) const noexcept; std::vector<Goal> goals() const; std::vector<Goal> eligible_goals() const;
 const DecisionEngine& decision_engine() const noexcept { return decision_; } const ActionModel& action_model() const noexcept { return action_model_; } const SelfModel& self_model() const noexcept { return self_model_; } const SelfStateModel& self_state_model() const noexcept { return self_state_model_; } const WorldModel& world() const noexcept { return world_; } const Memory& memory() const noexcept { return memory_; } BrainSnapshot snapshot() const; BrainState state() const;
private: static double compute_novelty(const Event& event, const std::vector<Event>& history); void replay(const Event& event); void sync_self_state(); bool append_goal_event(const Event& event); Prediction* find_latest_unresolved_prediction(const std::string& key) noexcept { for (auto it = predictions_.rbegin(); it != predictions_.rend(); ++it) if (it->key == key && !it->resolved) return &*it; return nullptr; } const Prediction* find_latest_unresolved_prediction(const std::string& key) const noexcept { for (auto it = predictions_.rbegin(); it != predictions_.rend(); ++it) if (it->key == key && !it->resolved) return &*it; return nullptr; } Prediction* find_prediction(std::uint64_t sequence) noexcept { for (auto& prediction : predictions_) if (prediction.created_sequence == sequence) return &prediction; return nullptr; } const Prediction* find_prediction(std::uint64_t sequence) const noexcept { for (const auto& prediction : predictions_) if (prediction.created_sequence == sequence) return &prediction; return nullptr; }
 mutable std::shared_mutex mutex_; BrainState state_{}; WorldModel world_{}; Memory memory_; std::unordered_map<std::string, Belief> beliefs_; std::vector<Prediction> predictions_; AssociationModel association_{}; CausalModel causal_{}; DecisionEngine decision_{}; ActionModel action_model_{}; AdaptationModel adaptation_{}; LearningLoop learning_loop_{}; AttentionModel attention_model_{}; ThreatModel threat_model_{}; ResilienceModel resilience_{}; EvolutionModel evolution_{}; EvolutionHistory evolution_history_{}; EvolutionController evolution_controller_; Planner planner_{}; ReflectionModel reflection_model_{}; KnowledgeModel knowledge_{}; SelfModel self_model_{}; SelfStateModel self_state_model_{}; SelfTestingModel self_testing_model_{}; GoalModel goals_model_{}; IntentModel intent_model_{}; StrategyModel strategy_model_{};
 DevelopmentalLearning developmental_learning_{}; AttentionSignal attention_state_{}; ThreatAssessment threat_state_{};
};
} // namespace jarvis::core