#include "jarvis/engineering/coordinator.hpp"
#include <algorithm>
namespace jarvis::engineering {
namespace { bool all(const std::vector<std::string>& a,const std::vector<std::string>& r){return std::all_of(r.begin(),r.end(),[&](const auto& x){return std::find(a.begin(),a.end(),x)!=a.end();});} }
int EngineeringCoordinator::risk_rank(AgentRisk r) noexcept{return static_cast<int>(r);}
bool EngineeringCoordinator::satisfies_permissions(const AgentDescriptor& a,const EngineeringTask& t) noexcept{return all(a.permissions,t.required_permissions);}
bool EngineeringCoordinator::satisfies_artifacts(const AgentDescriptor& a,const EngineeringTask& t) noexcept{return all(a.input_artifacts,t.input_artifacts)&&all(a.output_artifacts,t.expected_artifacts);}
std::vector<AgentCandidate> EngineeringCoordinator::discover(const EngineeringTask& t,const std::vector<AgentDescriptor>& agents) const { std::vector<AgentCandidate> out; if(!valid_task(t)) return out; for(const auto& a:agents){const bool v=valid_descriptor(a); const bool e=v&&all(a.capabilities,t.required_capabilities)&&satisfies_permissions(a,t)&&satisfies_artifacts(a,t)&&a.availability!=AgentAvailability::unavailable&&risk_rank(a.risk)<=risk_rank(t.maximum_risk)&&a.estimated_cost<=t.maximum_cost; out.push_back({a,0.0,e});} return out; }
std::vector<AgentCandidate> EngineeringCoordinator::rank(const EngineeringTask& t,const std::vector<AgentDescriptor>& agents) const {auto out=discover(t,agents); for(auto& c:out) if(c.eligible) c.score=c.agent.reliability*(c.agent.availability==AgentAvailability::available?1.0:0.5)/(1.0+c.agent.estimated_cost); std::stable_sort(out.begin(),out.end(),[](const auto&a,const auto&b){if(a.eligible!=b.eligible)return a.eligible>b.eligible;return a.score>b.score;}); return out;}
AgentResult EngineeringCoordinator::dispatch(const EngineeringTask& t,EngineeringAgent& agent,const EngineeringAuthorizer& auth,EngineeringExecutionBoundary& boundary) const {const auto d=agent.descriptor(); if(!valid_task(t)||!valid_descriptor(d)) return {false,d.id,t.id,"invalid task or agent descriptor",{}, {}}; auto c=discover(t,{d}); if(c.empty()||!c.front().eligible) return {false,d.id,t.id,"agent is not eligible for task",{}, {}}; if(!auth.authorize(t,d)) return {false,d.id,t.id,"execution authorization denied",{}, {}}; auto r=boundary.run(t,agent); if(r.agent_id.empty())r.agent_id=d.id; if(r.task_id.empty())r.task_id=t.id; return r;}
} // namespace jarvis::engineering
