#include "jarvis/engineering/message_bus.hpp"
#include <utility>
namespace jarvis::engineering {
AgentMessageBus::AgentMessageBus(MessageBusConfig c):config_(c){}
bool AgentMessageBus::valid_message(const AgentMessage&m)const noexcept{return !m.run_id.empty()&&!m.sender_id.empty()&&!m.recipient_id.empty()&&!m.message_id.empty()&&!m.correlation_id.empty()&&m.payload.size()<=config_.maximum_payload_bytes;}
MessageBusResult AgentMessageBus::register_agent(std::string id,AgentMessageHandler h){if(id.empty()||!h)return{false,0,"invalid agent registration"};std::lock_guard lock(mutex_);if(subscribers_.contains(id))return{false,0,"agent already registered"};subscribers_.emplace(std::move(id),Subscriber{std::move(h)});return{true,0,"agent registered"};}
MessageBusResult AgentMessageBus::unregister_agent(const std::string&id){if(id.empty())return{false,0,"invalid agent id"};std::lock_guard lock(mutex_);if(subscribers_.erase(id)==0)return{false,0,"agent not registered"};return{true,0,"agent unregistered"};}
MessageBusResult AgentMessageBus::send(AgentMessage m){AgentMessageHandler h;{std::lock_guard lock(mutex_);if(!valid_message(m))return{false,0,"invalid message"};auto it=subscribers_.find(m.recipient_id);if(it==subscribers_.end())return{false,0,"recipient not registered"};m.sequence=next_sequence_++;h=it->second.handler;}h(m);return{true,m.sequence,"message delivered"};}
std::size_t AgentMessageBus::registered_agents()const noexcept{std::lock_guard lock(mutex_);return subscribers_.size();}
AgentCommunicationEndpoint::AgentCommunicationEndpoint(AgentMessageBus&b,std::string id,std::string run,std::string ws,std::size_t max):bus_(b),agent_id_(std::move(id)),run_id_(std::move(run)),workspace_id_(std::move(ws)),state_(std::make_shared<State>()){state_->maximum_pending_messages=max;if(agent_id_.empty()||run_id_.empty()||max==0){state_->accepting=false;return;}const auto state=state_;const auto run_copy=run_id_;const auto ws_copy=workspace_id_;auto r=bus_.register_agent(agent_id_,[state,run_copy,ws_copy](const AgentMessage&m){AgentCommunicationEndpoint::receive(state,m,run_copy,ws_copy);});registered_=r.accepted;if(!registered_)state_->accepting=false;}
AgentCommunicationEndpoint::~AgentCommunicationEndpoint(){ {std::lock_guard lock(state_->mutex);state_->accepting=false;} if(registered_)bus_.unregister_agent(agent_id_); }
bool AgentCommunicationEndpoint::registered()const noexcept{return registered_;} const std::string& AgentCommunicationEndpoint::agent_id()const noexcept{return agent_id_;} const std::string& AgentCommunicationEndpoint::run_id()const noexcept{return run_id_;} const std::string& AgentCommunicationEndpoint::workspace_id()const noexcept{return workspace_id_;}
MessageBusResult AgentCommunicationEndpoint::send(std::string mid,std::string rid,std::string cid,AgentMessageType type,std::string payload){if(!registered_)return{false,0,"communication endpoint is not registered"};return bus_.send(AgentMessage{std::move(mid),0,run_id_,workspace_id_,agent_id_,std::move(rid),std::move(cid),type,std::move(payload)});}
void AgentCommunicationEndpoint::receive(const std::shared_ptr<State>&s,const AgentMessage&m,const std::string&run,const std::string&ws){if(m.run_id!=run||(!ws.empty()&&m.workspace_id!=ws))return;std::lock_guard lock(s->mutex);if(!s->accepting)return;if(s->pending_messages.size()>=s->maximum_pending_messages)s->pending_messages.pop_front();s->pending_messages.push_back(m);}
std::vector<AgentMessage> AgentCommunicationEndpoint::drain(){std::lock_guard lock(state_->mutex);std::vector<AgentMessage> out;out.reserve(state_->pending_messages.size());while(!state_->pending_messages.empty()){out.push_back(std::move(state_->pending_messages.front()));state_->pending_messages.pop_front();}return out;}
std::size_t AgentCommunicationEndpoint::pending()const noexcept{std::lock_guard lock(state_->mutex);return state_->pending_messages.size();}
} // namespace jarvis::engineering
