#include "jarvis/engineering/openai_astra_provider.hpp"
#include <cctype>
#include <cmath>
#include <cstddef>
#include <utility>
namespace jarvis::engineering { namespace {
constexpr std::string_view kSchema=R"JSON({"type":"object","properties":{"summary":{"type":"string"},"file_changes":{"type":"array","items":{"type":"object","properties":{"path":{"type":"string"},"content":{"type":"string"}},"required":["path","content"],"additionalProperties":false}},"evidence":{"type":"array","items":{"type":"object","properties":{"key":{"type":"string"},"value":{"type":"string"}},"required":["key","value"],"additionalProperties":false}}},"required":["summary","file_changes","evidence"],"additionalProperties":false})JSON";
std::size_t find_matching_object(std::string_view json,std::size_t start){if(start>=json.size()||json[start]!='{')return std::string_view::npos;std::size_t depth=0;bool escaped=false,in_string=false;for(std::size_t i=start;i<json.size();++i){const char ch=json[i];if(in_string){if(escaped)escaped=false;else if(ch=='\\')escaped=true;else if(ch=='"')in_string=false;continue;}if(ch=='"')in_string=true;else if(ch=='{')++depth;else if(ch=='}'&&--depth==0)return i;}return std::string_view::npos;}
std::size_t find_key_value_start(std::string_view json,std::string_view key,std::size_t from){const std::string marker="\""+std::string(key)+"\"";const auto key_begin=json.find(marker,from);if(key_begin==std::string_view::npos)return std::string_view::npos;std::size_t cursor=key_begin+marker.size();while(cursor<json.size()&&std::isspace(static_cast<unsigned char>(json[cursor])))++cursor;if(cursor>=json.size()||json[cursor]!=':')return std::string_view::npos;++cursor;while(cursor<json.size()&&std::isspace(static_cast<unsigned char>(json[cursor])))++cursor;return cursor;}
}
OpenAIAstraModelProvider::OpenAIAstraModelProvider(OpenAIAstraModelConfig config,HttpTransport transport) noexcept:config_(std::move(config)),transport_(std::move(transport)){}
ModelDescriptor OpenAIAstraModelProvider::descriptor()const{return {"openai-astra","openai",config_.model,{"code.implementation","code.review","code.verification","report"},config_.estimated_cost,config_.reliability};}
bool OpenAIAstraModelProvider::valid_config(const OpenAIAstraModelConfig& config)noexcept{return !config.model.empty()&&!config.token.empty()&&!config.endpoint.empty()&&(config.reasoning_effort=="low"||config.reasoning_effort=="medium"||config.reasoning_effort=="high"||config.reasoning_effort=="xhigh"||config.reasoning_effort=="max")&&std::isfinite(config.estimated_cost)&&config.estimated_cost>=0.0&&std::isfinite(config.reliability)&&config.reliability>=0.0&&config.reliability<=1.0;}
std::string OpenAIAstraModelProvider::escape_json(std::string_view value){std::string escaped;escaped.reserve(value.size()+16);for(const char ch:value){switch(ch){case '"':escaped+="\\\"";break;case '\\':escaped+="\\\\";break;case '\b':escaped+="\\b";break;case '\f':escaped+="\\f";break;case '\n':escaped+="\\n";break;case '\r':escaped+="\\r";break;case '\t':escaped+="\\t";break;default:if(static_cast<unsigned char>(ch)<0x20)escaped+=' ';else escaped+=ch;}}return escaped;}
std::string OpenAIAstraModelProvider::build_request_body(const OpenAIAstraModelConfig& config,const ModelRequest& request){const std::string input="Engineering objective:\n"+request.objective+"\n\nEngineering context:\n"+request.context;return "{\"model\":\""+escape_json(config.model)+"\",\"store\":false,\"reasoning\":{\"effort\":\""+escape_json(config.reasoning_effort)+"\"},\"instructions\":\"Return a structured engineering result. File changes must contain complete replacement file contents. Do not modify files outside the requested objective.\",\"input\":[{\"role\":\"user\",\"content\":[{\"type\":\"input_text\",\"text\":\""+escape_json(input)+"\"}]}],\"text\":{\"format\":{\"type\":\"json_schema\",\"name\":\"engineering_result\",\"strict\":true,\"schema\":"+std::string(kSchema)+"}}}";}
std::string OpenAIAstraModelProvider::extract_json_string(std::string_view json,std::string_view key,std::size_t from){const auto value_begin=find_key_value_start(json,key,from);if(value_begin==std::string_view::npos||value_begin>=json.size()||json[value_begin]!='"')return {};std::string value;bool escaped=false;for(std::size_t i=value_begin+1;i<json.size();++i){const char ch=json[i];if(escaped){switch(ch){case 'n':value+='\n';break;case 'r':value+='\r';break;case 't':value+='\t';break;case 'b':value+='\b';break;case 'f':value+='\f';break;case '"':value+='"';break;case '\\':value+='\\';break;default:value+=ch;}escaped=false;}else if(ch=='\\')escaped=true;else if(ch=='"')return value;else value+=ch;}return {};}
std::vector<ModelFileChange> OpenAIAstraModelProvider::extract_file_changes(std::string_view json){const auto value_begin=find_key_value_start(json,"file_changes",0);if(value_begin==std::string_view::npos||value_begin>=json.size()||json[value_begin]!='[')return {};std::size_t cursor=value_begin+1;std::vector<ModelFileChange> changes;while(cursor<json.size()&&json[cursor]!=']'){while(cursor<json.size()&&std::isspace(static_cast<unsigned char>(json[cursor])))++cursor;const auto object_begin=json.find('{',cursor);if(object_begin==std::string_view::npos)break;const auto object_end=find_matching_object(json,object_begin);if(object_end==std::string_view::npos)break;const auto object=json.substr(object_begin,object_end-object_begin+1);const auto path=extract_json_string(object,"path",0);const auto content=extract_json_string(object,"content",0);if(path.empty())break;changes.push_back({path,content});cursor=object_end+1;}return changes;}
ModelResponse OpenAIAstraModelProvider::generate(const ModelRequest& request){if(!valid_config(config_)||!valid_model_request(request)||!transport_)return {ModelProviderStatus::rejected,"openai",config_.model,{},{},{},"invalid configuration, request, or transport"};const HttpRequest http{"POST",config_.endpoint,{{"Authorization","Bearer "+config_.token},{"Content-Type","application/json"}},build_request_body(config_,request)};const auto response=transport_(http);if(response.status_code==401||response.status_code==403)return {ModelProviderStatus::rejected,"openai",config_.model,{},{},{},"openai authorization rejected"};if(response.status_code==408||response.status_code==429||response.status_code>=500)return {ModelProviderStatus::unavailable,"openai",config_.model,{},{},{},response.error.empty()?"openai temporarily unavailable":response.error};if(response.status_code<200||response.status_code>=300)return {ModelProviderStatus::failed,"openai",config_.model,{},{},{},response.error.empty()?"openai request failed":response.error};const auto output=extract_json_string(response.body,"text",0);if(output.empty())return {ModelProviderStatus::failed,"openai",config_.model,{},{},{},"openai response missing output text"};if(output.size()>request.maximum_output_bytes)return {ModelProviderStatus::failed,"openai",config_.model,{},{},{},"openai output limit exceeded"};const auto file_changes=extract_file_changes(output);return {ModelProviderStatus::succeeded,"openai",config_.model,output,file_changes,{{"model.provider","openai"},{"model.id",config_.model},{"model.reasoning_effort",config_.reasoning_effort}}, {}};}
} // namespace jarvis::engineering
